# SPDX-FileCopyrightText: 2023 Nikita Chernyi
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform prometheus-node-exporter installation tasks
  block:
    - name: Validate prometheus-node-exporter configuration
      when: prometheus_node_exporter_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install prometheus-node-exporter
      when: prometheus_node_exporter_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-prometheus-node-exporter
    - install-all
    - install-prometheus-node-exporter

- name: Perform prometheus-node-exporter uninstallation tasks
  block:
    - name: Uninstall prometheus-node-exporter
      when: not prometheus_node_exporter_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-prometheus-node-exporter
