---
- name: Fail if required prometheus-node-exporter settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - prometheus_node_exporter_uid
    - prometheus_node_exporter_gid
    - prometheus_node_exporter_server_fqn
    - prometheus_node_exporter_path_prefix
    - prometheus_node_exporter_container_network
