# SPDX-FileCopyrightText: 2023 Nikita Chernyi
# SPDX-FileCopyrightText: 2023 - 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "prometheus_node_exporter_server_fqn", "new": "prometheus_node_exporter_hostname" }
    - { "old": "prometheus_node_exporter_basicauth_enabled", "new": "prometheus_node_exporter_container_labels_metrics_middleware_basic_auth_enabled" }
    - "old": "prometheus_node_exporter_basicauth_user"
      "new": "<superseded by prometheus_node_exporter_container_labels_metrics_middleware_basic_auth_users>"
    - "old": "prometheus_node_exporter_basicauth_password"
      "new": "<superseded by prometheus_node_exporter_container_labels_metrics_middleware_basic_auth_users>"
    - { "old": "prometheus_node_exporter_basicauth_print", "new": "<removed>" }
    - { "old": "prometheus_node_exporter_docker_image_name_prefix", "new": "prometheus_node_exporter_container_image_registry_prefix" }
    - { "old": "prometheus_node_exporter_docker_image", "new": "prometheus_node_exporter_container_image" }
    - { "old": "prometheus_node_exporter_docker_image_registry_prefix", "new": "prometheus_node_exporter_container_image_registry_prefix" }
    - { "old": "prometheus_node_exporter_docker_image_registry_prefix_upstream", "new": "prometheus_node_exporter_container_image_registry_prefix_upstream" }
    - "old": "prometheus_node_exporter_docker_image_registry_prefix_upstream_default"
      "new": "prometheus_node_exporter_container_image_registry_prefix_upstream_default"
    - { "old": "prometheus_node_exporter_docker_image_force_pull", "new": "prometheus_node_exporter_container_image_force_pull" }

- name: Fail if required Prometheus node exporter settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - prometheus_node_exporter_uid
    - prometheus_node_exporter_gid
    - prometheus_node_exporter_container_network

- name: Run if Traefik is enabled
  when: prometheus_node_exporter_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Prometheus node exporter are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - prometheus_node_exporter_container_labels_traefik_hostname
        - prometheus_node_exporter_container_labels_traefik_path_prefix
